sudo: required
dist: trusty
language: node_js
node_js:
  - 6
env:
  - CC=clang CXX=clang++ npm_config_clang=1
script: npm run ci
before_install:
 - sudo apt-get update
 - sudo apt-get install xvfb gnome-keyring libsecret-1-dev
