sudo: false
language: node_js
node_js:
  - 5
# addons:
#   apt:
#     packages:
#       - xvfb
#       - gnome-keyring
#       - libgnome-keyring-dev
env:
  # - CC=clang CXX=clang++ npm_config_clang=1
  - CXX=g++-4.8 CI=1
# script: xvfb-run ./script/cibuild

# Need to add CXX env flag and g++-4.8 (in ubuntu-toolchain-r-test source)
# @see https://github.com/travis-ci/travis-ci/issues/4771
# @see https://github.com/redis/hiredis-node/blob/master/.travis.yml
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libkrb5-dev
    - libgnome-keyring-dev

script: npm run-script ci
# Post build notifications to the Integrations Flowdock
notifications:
  flowdock: e3dc17bc8a2c1b3412abe3e5747f8291
